/* -*- Mode: C++; tab-width: 4 -*- */
//-----------------------------------------------------------------------------
// Project            : 
// File Name          : clk_div_testMain.cpp
// Original Author    : 
// Description        : 
//-----------------------------------------------------------------------------
// This file was generated by v2sysc.py
//------------------------------------------------------------------------------

#include "systemc.h"
#include "spike_iss_test.h"
#include "trace_control.h"
#include <iomanip>
#include <sstream>
using namespace std;

int sc_main( int argc, char* argv[] ) {

    bool   traceEnable   = false;
    bool   randomize     = false;
    bool   dumpData      = false;
    bool   noCheck       = false;
    int    traceControl  = TRACE_ALL;
    int    traceDepth    = 5;
    int    cmdNumber     = 3;
    int    testNumber    = 0;
    int    loopCount     = 1;
    int    spike_argc;

    spike_argc = 0;
    //char*  spike_argv = new char[argc];
    char*  spike_argv[argc];
    std::string traceType;

    //-----------------------------------------------------------------------------//
    //---                       Check Arguments                                ----//
    //-----------------------------------------------------------------------------//
    if( argc == 1 ) {
        cout << "Usage:" << endl << endl;
        cout << "    testMain.exe command-number test-number [-random] [-dump]" << endl;
        cout << "                [-traceio|wire|reg|temp|all][-loop loop-count] [-nocheck]" << endl;
        cout << endl;
        cout << "Options:" << endl << endl;
        cout << "    -random  specifies that data is to be generated randomly." << endl;
        cout << "    -dump    displays response and expected data." << endl;
        cout << "    -trace   enables signal tracing." << endl;
        cout << "    -loop    specifies that the test is to be run loop-count times." << endl;
        cout << "    -nocheck disable checking of expected results against actual results." << endl;
        cout << endl;
        cmdNumber = 0;
    }
    else if( argc == 2 ) {
        cmdNumber  = atoi( argv[1] );
        testNumber = 0;
    }
    else if( argc > 2 ) {
        cmdNumber  = atoi( argv[1] );
        testNumber = atoi( argv[2] );
    }

    if( argc > 3 ) {
        for ( int i = 3; i < argc; i++ ) {
            if ( !strcmp( argv[i], "-trace" ) ) {
                traceEnable = true;
				if( argc > (i + 1) ) {
                    traceType   = argv[++i];
		            if( traceType == "io" ) {
		                traceControl = TRACE_IO;
		            }
		            else if( traceType == "wire" ) {
		                traceControl = TRACE_WIRE;
		            }
		            else if( traceType == "reg" ) {
		                traceControl = TRACE_REG;
		            }
		            else if( traceType == "temp" ) {
		                traceControl = TRACE_TEMP;
		            }
		            else if( traceType == "all" ) {
		                traceControl = TRACE_ALL;
		            }
				    else {
                        cerr << "ERROR: Unknown trace type, \"" << argv[i] << "\". Expecting io, wire, reg, temp or all." << endl << endl;
                        return( -1 );
				    }
				}
				else {
                    cerr << "ERROR: Missing trace type." << endl << endl;
                    return( -1 );
				}
            }
            else if ( !strcmp( argv[i], "-traceDepth" ) ) {
                traceDepth = atoi( argv[++i] );
            }
            else if ( !strcmp( argv[i], "-random" ) ) {
                randomize = true;
            }
            else if ( !strcmp( argv[i], "-loop" ) ) {
                loopCount = atoi( argv[++i] );
            }
            else if ( !strcmp( argv[i], "-dump" ) ) {
                dumpData = true;
            }
            else if ( !strcmp( argv[i], "-nocheck" ) ) {
                noCheck = true;
            }
            else {
                cout << "argv[" << i << "] = " << argv[i] << endl;
                spike_argv[spike_argc] = argv[i];
                spike_argc++;
            }
        }
    }

    sc_clock clk( "clk", 5.0, SC_NS );
    spike_iss_test i_spike_iss_test ( "spike_iss_test" );
    i_spike_iss_test.clk( clk );

    i_spike_iss_test.setCmdNumber( cmdNumber );
    i_spike_iss_test.setTestNumber( testNumber );
    i_spike_iss_test.setLoopCount( loopCount );
    i_spike_iss_test.setRandomize( randomize );
    i_spike_iss_test.setDumpData( dumpData );
    i_spike_iss_test.setNoCheck( noCheck );
    i_spike_iss_test.setTraceControl( traceControl );
    i_spike_iss_test.setTraceEnable( traceEnable );
	
	if( traceEnable ) {
	    i_spike_iss_test.signalTrace( traceControl, traceDepth );
	}

    i_spike_iss_test.i_spike_iss->argc = spike_argc;
    i_spike_iss_test.i_spike_iss->argv = spike_argv;

    sc_start( );

    cout << "Time = "<< sc_time_stamp() << endl;

    return( 0 );

}
